jenkins:
  systemMessage: "Welcome to the ChocolatinePowered Marvin Jenkins 
Instance."

users:
  - id: chocolateen
    password: ${USER_CHOCOLATEEN_PASSWORD}
  - id: vaugie_g
    password: ${USER_VAUGIE_G_PASSWORD}
  - id: i_dont_know
    password: ${USER_I_DONT_KNOW_PASSWORD}
  - id: nasso
    password: ${USER_NASSO_PASSWORD}

authorizationStrategy:
  roleBased:
    roles:
      - name: admin
        description: "Marvin master"
        permissions:
          - "Overall/Administer"
        users:
          - "chocolateen"
      - name: ape
        description: "Pedagogical team member"
        permissions:
          - "Job/Build"
          - "Job/Workspace"
        users:
          - "i_dont_know"
      - name: gorilla
        description: "Group Obsessively Researching Innovation Linked to 
Learning and Accomplishment"
        permissions:
          - "Job/Build"
          - "Job/Workspace"
          - "Job/Configure"
          - "Job/Delete"
          - "Job/Move"
          - "Run/Delete"
        users:
          - "vaugie_g"
      - name: assist
        description: "Assistant"
        permissions:
          - "Job/Read"
          - "Job/Workspace"
        users:
          - "nasso"

folder:
  name: "Tools"
  description: "Folder for miscellaneous tools."

jobs:
  - name: "clone-repository"
    folder: "Tools"
    description: "Clone repository job"
    parameters:
      - string:
          name: "GIT_REPOSITORY_URL"
          description: "Git URL of the repository to clone"

  - name: "SEED"
    folder: "Tools"
    description: "Seed job to create other jobs"
    parameters:
      - string:
          name: "GITHUB_NAME"
          description: "GitHub repository owner/repo_name"
      - string:
          name: "DISPLAY_NAME"
          description: "Display name for the job"


